packages:
  # all packages in subdirs of packages/ and components/
  - "packages/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
allowBuilds:
  '@parcel/watcher': true
  core-js: false
  cssnano: false
  esbuild: true
  fsevents: false
minimumReleaseAgeExclude:
  - eslint-plugin-vue@10.11.1
packageExtensions:
  vue-template-compiler@2.6.11:
    dependencies:
      vue: 2.6.11
