export declare const V3_BACKUP_VERSION: 9;
export declare const V3_BACKUP_LEGACY_VERSION: 3;
export declare const V3_BACKUP_PREVIOUS_VERSION: 7;
export declare const V3_BACKUP_EXACT_MATCH_VERSION: 4;
export declare const V3_BACKUP_DISABLED_ORIGINS_VERSION: 5;
export declare const V3_BACKUP_REDIRECT_EXCLUSIONS_VERSION: 6;
export declare const V3_BACKUP_REDIRECT_FUNCTION_VERSION: 7;
export declare const V3_BACKUP_STATIC_REDIRECT_HEADERS_VERSION: 8;
export declare const V3_BACKUP_RESPONSE_MODE_VERSION: 9;
